### PR TITLE
fix: merge branch 'develop' into alpha

### PR DESCRIPTION
**Pull request by mrehan27**
Complete each step to get your pull request merged in. [Learn more about the workflow this project uses](https://github.com/customerio/customerio-android/develop/docs/dev-notes/GIT-WORKFLOW.md).
- [ ] [Assign members of your team](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to review the pull request.
- [ ] Wait for pull request status checks to complete. If there are problems, fix them until you see that [all status checks are passing](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fsymfony.com%2Fdoc%2F4.3%2F_images%2Fdocs-pull-request-symfonycloud.png&f=1&nofb=1).
- [ ] Wait until the pull request has been reviewed *and approved* by a teammate
- [ ] After pull request is approved, and you determine it's ready **add the label "Ready to merge"** to the pull request and it will automatically be merged.

### CODE REVIEW

**Review by levibostian — COMMENTED** [review]
I think that this PR was made to merge in the production hotfix that was made? 

If that's true, I suggest we close this PR and you instead run some git commands to deploy the `main` branch hotfix commits into `alpha`. 

I suggest this because:
* By merging in this PR, we may make our git commit version history a little messy. If you were to merge the commits from `main` branch into `alpha` branch, no new commits would be introduced to the commit history. The hotfix commit in `main` would just be copied over to `alpha` but if this PR gets merged, then a new commit would be made (for the merged PR) and eventually the hotfix commit in `main` would be also present in the git commit history. 2 commits for the same change. 
* Since the hotfix PR was approved to get merged into `main`, the code is approved by the team to be used. So, I think you can freely use it in `alpha` without the attention of our team.

**Comment by mrehan27** [comment]
Thanks for pointing this out @levibostian. I agree, we should avoid multiple commits for same changes.

I think we can merge this to `alpha` using one of the following options:

- Merge `develop` to `alpha` using `git merge`, this will add all 4 commits to `alpha` branch and we might not get any conflicts when `alpha` branch is eventually merged to `main` and `develop`, the changes will be identical to this PR in this case.
- Cherry pick the [commit](https://github.com/customerio/customerio-android/commit/a6dcf3c190d25cc7052aa3e749b6258beafed1f7) with hotfix. This will create a conflict in `CHANGELOG` and `Version` later when `alpha` is merged to `main`, but not an issue as the workflow handles this and can be resolved in the PR generated for this.

If you have a recommendation, please let me know. Else I'll go with the second one (cherry-picking the commit). But for both these options, I would need to push to `alpha` directly. And I'm not sure if direct push to `alpha` will auto-trigger the release or do we need to run it manually? Can you please confirm this?

**Comment by levibostian** [comment]
I recommend option #1 of doing a git merge. It's easier, I think it will result in less git issues in the future for the `alpha` branch, but also it seems logical to me. Since `main` branch is what's in production and `alpha` always contains everything that production code contains *and more*, it makes sense to me for `alpha` to always contain all commits that `main` does *and more*. 

I believe that `develop`, `alpha`, and `beta` branches should always have commits *ahead* of `main`, never behind. `main` should be the only branch that is behind these branches until the next production deployment is done.

**Comment by mrehan27** [comment]
Thanks for the details. Makes sense to me. I'm then closing this PR and updating `alpha` after `git merge` to roll out these changes.

> It might be a good idea to duplicate this CI task to also automatically update alpha or beta branch after main changes, too?

Yes, I too think it is a good idea. Because whatever gets merged to `main`, would probably always be needed back in `alpha` or `beta`. Updating CI server to handle this will not only make it easier for team but will also make it less error prone.

**Pull request closed without merging**
